spring.application.name=app

# Porta do servidor
server.port=8080

# Configura  o do DataSource para PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/clinica
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# Configura  o do Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.main.allow-bean-definition-overriding=true


logging.level.org.springframework=DEBUG
logging.level.com.ag.app=DEBUG
logging.level.org.hibernate=WARN
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.file.name=logs/app.log
logging.file.max-size=10MB
logging.file.max-history=10

# JWT
app.jwt.secret=uma-chave-secreta-muito-grande-e-segura-para-hs256-12345678901234567890
app.jwt.expiration=3600000